# generated by datamodel-codegen:
#   filename:  cose_schema.json
#   version:   0.76.2

from __future__ import annotations

from enum import Enum

from pydantic import Base64Str, BaseModel, ConfigDict, Field, RootModel, StrictStr


class Algorithm(str, Enum):
    """The hashing function used to compute the hash value."""

    SHA256 = "sha256"


class PayloadHash(BaseModel):
    """Specifies the hash algorithm and value for the content."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    algorithm: Algorithm = Field(
        ..., description="The hashing function used to compute the hash value"
    )
    value: StrictStr = Field(..., description="The hash value for the content")


class EnvelopeHash(BaseModel):
    """Specifies the hash algorithm and value for the COSE envelope."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    algorithm: Algorithm = Field(
        ..., description="The hashing function used to compute the hash value"
    )
    value: StrictStr = Field(..., description="The hash value for the envelope")


class Data(BaseModel):
    """Information about the content associated with the entry."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    payload_hash: PayloadHash | None = Field(
        default=None,
        alias="payloadHash",
        description="Specifies the hash algorithm and value for the content",
    )
    envelope_hash: EnvelopeHash | None = Field(
        default=None,
        alias="envelopeHash",
        description="Specifies the hash algorithm and value for the COSE envelope",
    )
    aad: Base64Str | None = Field(
        default=None,
        description="Specifies the additional authenticated data required to verify the signature",
    )


class CoseV001Schema(BaseModel):
    """Schema for cose object."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: Base64Str | None = Field(default=None, description="The COSE Sign1 Message")
    public_key: Base64Str = Field(
        ..., alias="publicKey", description="The public key that can verify the signature"
    )
    data: Data | None = Field(
        default=None, description="Information about the content associated with the entry"
    )


class CoseSchema(RootModel[CoseV001Schema]):
    root: CoseV001Schema = Field(..., description="COSE for Rekord objects", title="COSE Schema")
