name: check for new Rekor releases
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions: {}

jobs:
  check-rekor-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: pyproject.toml
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: get latest rekor release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/sigstore/rekor/releases/latest -q .tag_name > codegen/version

      - name: codegen
        run: |
          make dev
          source env/bin/activate
          ./codegen/codegen.sh

      - name: create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "[BOT] Regenerate for new Rekor version"
          branch: update-rekor
          branch-suffix: timestamp
          title: "[BOT] bump Rekor"
          body: |
            This is an automated pull request, bumping the code generation
            to match the latest Rekor release.

            Please review manually before merging.
          assignees: "woodruffw"
          reviewers: "woodruffw"
