name: check for new Rekor releases
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  check-rekor-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version-file: pyproject.toml
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: get latest rekor release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/sigstore/rekor/releases/latest -q .tag_name > codegen/version

      - name: codegen
        run: |
          make dev
          source env/bin/activate
          ./codegen/codegen.sh

      - name: create PR
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7
        with:
          commit-message: "[BOT] Regenerate for new Rekor version"
          branch: update-rekor
          branch-suffix: timestamp
          title: "[BOT] bump Rekor"
          body: |
            This is an automated pull request, bumping the code generation
            to match the latest Rekor release.

            Please review manually before merging.
          assignees: "woodruffw"
          reviewers: "woodruffw"
