name: Tests

on:
  pull_request:
  push:
    branches:
      - main


permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  smoketest-dists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: pyproject.toml

      - run: |
          python -m pip install build
          python -m build

          for dist in dist/*; do
            python -m venv /tmp/smoketest-env

            /tmp/smoketest-env/bin/python -m pip install "${dist}"
            /tmp/smoketest-env/bin/python -c 'import rekor_types; print(rekor_types.__version__)'

            rm -rf /tmp/smoketest-env
          done
