name: Tests

on:
  pull_request:
  push:
    branches:
      - main


permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  smoketest-dists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: pyproject.toml

      - run: |
          python -m pip install build
          python -m build

          for dist in dist/*; do
            python -m venv /tmp/smoketest-env

            /tmp/smoketest-env/bin/python -m pip install "${dist}"
            /tmp/smoketest-env/bin/python -c 'import rekor_types; print(rekor_types.__version__)'

            rm -rf /tmp/smoketest-env
          done
